/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface RSVP {
  'id' : bigint,
  'mealPreference' : string,
  'name' : string,
  'submittedAt' : Time,
  'email' : string,
  'message' : string,
  'attending' : boolean,
}
export type Time = bigint;
export interface _SERVICE {
  'deleteRSVP' : ActorMethod<[bigint], undefined>,
  'getAllRSVPs' : ActorMethod<[], Array<RSVP>>,
  'getRSVPCount' : ActorMethod<
    [],
    { 'total' : bigint, 'notAttending' : bigint, 'attending' : bigint }
  >,
  'submitRSVP' : ActorMethod<[string, string, boolean, string, string], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];