/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const RSVP = IDL.Record({
  'id' : IDL.Nat,
  'mealPreference' : IDL.Text,
  'name' : IDL.Text,
  'submittedAt' : Time,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'attending' : IDL.Bool,
});

export const idlService = IDL.Service({
  'deleteRSVP' : IDL.Func([IDL.Nat], [], []),
  'getAllRSVPs' : IDL.Func([], [IDL.Vec(RSVP)], ['query']),
  'getRSVPCount' : IDL.Func(
      [],
      [
        IDL.Record({
          'total' : IDL.Nat,
          'notAttending' : IDL.Nat,
          'attending' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'submitRSVP' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Bool, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const RSVP = IDL.Record({
    'id' : IDL.Nat,
    'mealPreference' : IDL.Text,
    'name' : IDL.Text,
    'submittedAt' : Time,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'attending' : IDL.Bool,
  });
  
  return IDL.Service({
    'deleteRSVP' : IDL.Func([IDL.Nat], [], []),
    'getAllRSVPs' : IDL.Func([], [IDL.Vec(RSVP)], ['query']),
    'getRSVPCount' : IDL.Func(
        [],
        [
          IDL.Record({
            'total' : IDL.Nat,
            'notAttending' : IDL.Nat,
            'attending' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'submitRSVP' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Bool, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };