/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const GuestMessage = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'submittedAt' : Time,
  'message' : IDL.Text,
});

export const idlService = IDL.Service({
  'deleteMessage' : IDL.Func([IDL.Nat], [], []),
  'getAllMessages' : IDL.Func([], [IDL.Vec(GuestMessage)], ['query']),
  'getMessageCount' : IDL.Func([], [IDL.Nat], ['query']),
  'submitMessage' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const GuestMessage = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'submittedAt' : Time,
    'message' : IDL.Text,
  });
  
  return IDL.Service({
    'deleteMessage' : IDL.Func([IDL.Nat], [], []),
    'getAllMessages' : IDL.Func([], [IDL.Vec(GuestMessage)], ['query']),
    'getMessageCount' : IDL.Func([], [IDL.Nat], ['query']),
    'submitMessage' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };